### ISSUE TITLE
遍历变量数组下标溢出

### ISSUE THREAD

**Issue by ShuaiHuang** [voidii/cs24_hw1#1]
[hw1.cpp](https://github.com/voidii/cs24_hw1/blob/master/hw1.cpp) https://github.com/voidii/cs24_hw1/commit/102f1e573b7902efbbdba5940c1e918536199b0d
第9行和第10行的遍历下标变量`i`和`j`是int型变量, 而作为下标最大范围`n`是double类型, double类型比int类型变量的表示范围要大, `i`和`j`遍历到最大值后, 产生溢出, 变量变为`0`, 产生死循环.

@voidii TODO: 
1. 反向推导一下, 如何在Visual Studio中debug这种问题?
2. 尝试修正这一bug.

**Comment by voidii** [comment]
已解决

**Comment by ShuaiHuang** [comment]
> 已解决

第9行和第10行的遍历下标变量`i`和`j`是int型变量, 而作为下标最大范围n是double类型, double类型比int类型变量的表示范围要大, `i`和`j`遍历到最大值后, 产生溢出, 变量变为0, 产生死循环.

*解决问题后最好标注一下，是怎么样解决这个问题的，这样才是一个有效的问题闭环方式。*

**Comment by voidii** [comment]
其实就是统一一下类型就可以了，不过用double也没有解决我的最终问题也就是时间到底是多少，我后来换了个思路，把时间固定然后求sum的和，就解决了
